### PR TITLE
fix: fix IPInfo enrichment issue (#492)

### LINKED ISSUE #492: [BUG] Mihari `loc` KeyError
### **Describe the bug**
An existing Feed rule which has worked since inception is beginning to return a `*A* 'KeyError' *occured in background*: key not found: "loc"` error.

### **Steps to reproduce**
1. Query the API directly first, using `curl -X POST https://threatfox-api.abuse.ch/api/v1/ -d '{ "query": "malwareinfo", "malware": "Cobalt Strike", "limit": 100 }'` which returns results as expected:

``` json
{
    "query_status": "ok",
    "data": [
        {
            "id": "726106",
            "ioc": "123.56.156.53:80",
            "threat_type": "botnet_cc",
            "threat_type_desc": "Indicator that identifies a botnet command&control server (C&C)",
            "ioc_type": "ip:port",
            "ioc_type_desc": "ip:port combination that is used for botnet Command&control (C&C)",
            "malware": "win.cobalt_strike",
            "malware_printable": "Cobalt Strike",
            "malware_alias": "Agentemis,BEACON,CobaltStrike",
            "malware_malpedia": "https:\/\/malpedia.caad.fkie.fraunhofer.de\/details\/win.cobalt_strike",
            "confidence_level": 100,
            "first_seen": "2022-06-25 09:10:33 UTC",
            "last_seen": null,
            "reference": null,
            "reporter": "drb_ra",
            "tags": [
                "ALIBABA-CN-NET Hangzhou Alibaba Advertising Co.Ltd.",
                "CobaltStrike"
            ]
        }
    ]
}
```

2. Run with Mihari using `mihari search /rules/feed_threatfox.yml`, with the following rule:

``` yaml
title: Cobalt Strike C2
author: Sajid Nawaz Khan
created_on: 2022-01-03
description: Imports high-fidelity and validated Cobalt Strike C2s from ThreatFox.
tags: ["C2"]
allowed_data_types:
  - ip
ignore_old_artifacts: true
ignore_threshold: 30
queries:
  - analyzer: feed
    query: https://threatfox-api.abuse.ch/api/v1/
    http_request_method: "POST"
    http_request_payload:
      query: "malwareinfo"
      malware: "Cobalt Strike"
      limit: 500
    http_request_payload_type: "application/json"
    selector: "map(&:data).unwrap.map(&:ioc).map { |v| v.start_with?('http://', 'https://') ? v :  v.split(':').first }"
```

### **Expected behavior**
Should process feed and add matching IOCs into the local sqlite database. Here is the `stdout` output from when the query worked around a week ago:

``` json
{
  "title": "Cobalt Strike C2",
  "description": "Imports high-fidelity and validated Cobalt Strike C2s from ThreatFox.",
  "artifacts": [
    "18.142.179.129",
    "45.195.149.175"
  ],
  "source": "d8dc147e-fdf6-36bb-9bd7-61745c303fdd",
  "tags": [
    "C2"
  ]
}

```

Running the `selector` manually with `cat cs.json | jr "map(&:data).unwrap.map(&:ioc).map { |v| v.start_with?('http://', 'https://') ? v :  v.split(':').first }"` correctly returns `"123.56.156.53"` as expected.

### **Actual behavior**
Returns the following error, consistently:

```
*A* `KeyError` *occured in background*: key not found: "loc"
```/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/ipinfo.rb:30:in `fetch'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/ipinfo.rb:30:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/enrichers/ipinfo.rb:42:in `query'
/var/lib/gems/2.7.0/gems/memist-2.0.2/lib/memist/class_methods.rb:21:in `block in memoize'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/models/autonomous_system.rb:18:in `build_by_ip'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/models/artifact.rb:102:in `enrich_autonomous_system'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/models/artifact.rb:109:in `enrich_all'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/analyzers/base.rb:115:in `block in enriched_artifacts'
/var/lib/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
/var/lib/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'```
```

### **Screenshots**
N/A, see above for the error.

### **System Information:**

- OS: Ubuntu
- Ruby version: 2.7.0
- Mihari version: mihari-3.12.0 (Sorry! Manually patched with Shodan Fix: https://github.com/ninoseki/mihari/pull/425)

Appreciate this is an older instance of Mihari, but would appreciate any guidance on how to troubleshoot and resolve this error. Thanks!

### PR DESCRIPTION
**Pull request by ninoseki**
Fix #492

### CODE REVIEW

**Comment by abdullahdevrel** [comment]
Hi, I am the DevRel of IPinfo, and I was curious why IPinfo has been removed from the project. Is there anything we can do to get back into the project? Thank you.

**Comment by ninoseki** [comment]
Absolutely there is nothing wrong with IPInfo.
I just want to make this project dependency free as much as possible, which means not using a commercial service as much as possible.

Also, this project uses IPInfo's `GET https://ipinfo.io//{ip}/json` API endpoint to enrich an IP data. I'd say it's an optional feature not mandatory. So I decided to switch to MMDB.

**Comment by abdullahdevrel** [comment]
I understand that.

Mihari is one of the most popular projects that use our service, so we are proud of this project and the work you do. I appreciate your decision to still make room for us, even though it is an optional feature. I would like to say that our data is more accurate, so if you find any case where you are impacted by IP geolocation accuracy, we would be honored to be the de facto IP geolocation provider again!

If you want, you can also take a look at our [free IP databases](https://ipinfo.io/products/free-ip-database). The databases are licensed under CC-BY-SA 4.0. However, they are a bit out of the project's scope as they are not an API service but rather static MMDB files. But since they are databases, users can essentially make infinite queries against them. If you decide to check them out in the future, feel free to ping me.

**Comment by ninoseki** [comment]
Yes there is no doubt that IPInfo is more accurate than MMDB. 
I changed my mind and I will revert IPInfo removal.
- If a user set IPInfo API key (token), use IPInfo
- If a user doesn't set IPInfo API key, use public MMDB API

**Comment by abdullahdevrel** [comment]
Awesome! I am very glad I reached out!

I want to mention that we do support up to 1,000 requests per day without an access token solely to support projects like yours. You can make 1,000 requests per month without an API key, but if you have a free API token, you can make up to 50,000 requests per month. Also, we support bulk/batch lookups: https://ipinfo.io/blog/bulk-ip-lookups/

**Pull request merged**
